### PR TITLE
filter out null values when iterating over select_jsonpath results

### LINKED ISSUE #232: select_jsonpath fails on missing json keys
When using `select_jsonpath` to extract one or more values from a JSON object, the function does not handle missing values gracefully and will fail the entire rule.

The test introduced in #209 unfortunately looks like it tests for the correct behavior, but the test harness is not exactly the same as the production code.

Thus we need to filter out null values in the function itself. The NPE is an unfortunate sideeffect of the Java streams map collector, rather than the overall "null-ness" of a value in a map.

### PR DESCRIPTION
**Pull request by kroepke**
fix #232

### CODE REVIEW

File: plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/SelectJsonPath.java [hunk 1]
```diff
@@ -73,12 +74,14 @@ public SelectJsonPath(ObjectMapper objectMapper) {
...
+        // filter null values out first
         return paths
                 .entrySet().stream()
-                .collect(toMap(
-                        Map.Entry::getKey,
-                        e -> unwrapJsonNode(e.getValue().read(json, configuration))
-                ));
+                .map(entry -> Maps.immutableEntry(entry.getKey(), unwrapJsonNode(entry.getValue().read(json, configuration))))
+                .filter(entry -> entry.getValue() != null)
+                .collect(toMap(Map.Entry::getKey, Map.Entry::getValue));
```
Comment (joschi) [inline plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/SelectJsonPath.java]: Call me old-fashioned, but couldn't this be solved shorter and faster with the following change?
```diff
diff --git a/plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/SelectJsonPath.java b/plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/SelectJsonPath.java
index 2ea6222..b18f249 100644
--- a/plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/SelectJsonPath.java
+++ b/plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/SelectJsonPath.java
@@ -19,7 +19,6 @@ package org.graylog.plugins.pipelineprocessor.functions.json;
 import com.fasterxml.jackson.databind.JsonNode;
 import com.fasterxml.jackson.databind.ObjectMapper;
 import com.google.common.collect.ImmutableList;
-import com.google.common.collect.Maps;
 import com.google.inject.TypeLiteral;
 import com.jayway.jsonpath.Configuration;
 import com.jayway.jsonpath.JsonPath;
@@ -31,9 +30,11 @@ import org.graylog.plugins.pipelineprocessor.ast.functions.FunctionArgs;
 import org.graylog.plugins.pipelineprocessor.ast.functions.FunctionDescriptor;
 import org.graylog.plugins.pipelineprocessor.ast.functions.ParameterDescriptor;

+import javax.annotation.Nullable;
 import javax.inject.Inject;
 import java.io.IOException;
 import java.util.Collections;
+import java.util.HashMap;
 import java.util.Map;

 import static com.google.common.collect.ImmutableList.of;
@@ -74,16 +75,14 @@ public class SelectJsonPath extends AbstractFunction<Map<String, Object>> {
         if (json == null || paths == null) {
             return Collections.emptyMap();
         }
-        // a plain .collect(toMap(...)) will fail on null values, because of the HashMap#merge method in its implementation
-        // since json nodes at certain paths might be missing, the value could be null.
-        // filter null values out first
-        return paths
-                .entrySet().stream()
-                .map(entry -> Maps.immutableEntry(entry.getKey(), unwrapJsonNode(entry.getValue().read(json, configuration))))
-                .filter(entry -> entry.getValue() != null)
-                .collect(toMap(Map.Entry::getKey, Map.Entry::getValue));
+        final Map<String, Object> map = new HashMap<>();
+        for (Map.Entry<String, JsonPath> entry : paths.entrySet()) {
+            map.put(entry.getKey(), unwrapJsonNode(entry.getValue().read(json, configuration)));
+        }
+        return map;
     }

+    @Nullable
     private Object unwrapJsonNode(Object value) {
         if (!(value instanceof JsonNode)) {
             return value;
```

At least `FunctionsSnippetsTest` is green with that.

Comment (kroepke) [reply plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/SelectJsonPath.java]: Sure, I don't care which way, I just added to what was there previously.
